#adapted from example in docker documentation
version: '3'

services:
  web:
    build: .
    volumes:
       - .:/code
    expose:
       - 8000
    user: "1000:1001" #System dependent   
    command:  python /code/mysite/manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - web
    ports:
       - 8080:80
    links:
      - web:web
